name: Java CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@v4
        with:
          fetch-depth: 30 # Gets the last 30 commits so the changelog might work
      # Always run on Java 17 or higher, Loom needs it
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Build with Gradle
        env:
          FTB_MAVEN_TOKEN: ${{ secrets.FTB_MAVEN_TOKEN }}
          SAPS_TOKEN: ${{ secrets.SAPS_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew build publish --stacktrace --no-daemon
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            build/libs
